{% set name = "findorb" %}
{% set version = "0.0.20210525" %}
{% set sha_findorb = "a663899ba5831665e2138dbdb689a5f7cf126ea6" %}
{% set sha_lunar = "831a65c7c1dfb2caf645c843bb5ceba645d97c64" %}
{% set sha_jpl_eph = "03d6ee91506eb71d0a140117fe2bcda3535cd0ce" %}
{% set sha_sat_code = "1f14de2d60e5a8804fcfa4fad36baeb5383010f0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
#  - url: https://github.com/Bill-Gray/find_orb/archive/{{ sha_findorb }}.tar.gz
#    sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
#    folder: sources/find_orb
  - path: /astro/users/mjuric/projects/github.com/mjuric/find_orb
    folder: sources/find_orb
  - url: https://github.com/Bill-Gray/lunar/archive/{{ sha_lunar }}.tar.gz
    sha256: c3bf22a47af903becebe5d570ec57b85db3ed6337e522c0bf8922d6695b64ae4
    folder: sources/lunar
  - url: https://github.com/Bill-Gray/jpl_eph/archive/{{ sha_jpl_eph }}.tar.gz
    sha256: fa53af1f4a4d44cf519e45aa2761f1833382a539f0ac8165a6c1ab7fe5207447
    folder: sources/jpl_eph
  - url: https://github.com/Bill-Gray/sat_code/archive/{{ sha_sat_code }}.tar.gz
    sha256: 58d9c18c225bba1598a52ac68c0bfb2d2d95b1b4614ae9396f98611e4d66a392
    folder: sources/sat_code

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - curl
    - git
  host:
    - cpp-filesystem  # [osx]
    - ncurses
  run:
    - ncurses
    - findorb-data-de430t

test:
  files:
    - single.psv
    - fo.expected.out

about:
  home: https://github.com/Bill-Gray/find_orb
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: sources/find_orb/LICENSE
  summary: 'Orbit determination from observations'
  description: |
    Find_Orb can take a set of observations of an asteroid, comet, or natural or artificial satellite,
    given in the MPC (Minor Planet Center) format, the newer ADES astrometric format,
    and/or the NEODyS or AstDyS formats, and find the corresponding orbit.
  doc_url: https://www.projectpluto.com/find_orb.htm
  dev_url: https://github.com/Bill-Gray/find_orb

extra:
  recipe-maintainers:
    - mjuric
    - moeyensj
